ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /imu/data
    imu0_config: [false, false, false,  # Position: [x, y, z]
                  false, false, false,  # Linear velocity: [x, y, z]
                  true, true, true,     # Orientation: [roll, pitch, yaw]
                  false, false, false,  # Angular velocity: [x, y, z]
                  true, true, true,     # Orientation variance: [roll, pitch, yaw]
                  false, false, false]  # Angular velocity variance: [x, y, z]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    odom1: /radar_odom
    odom1_config: [true, true, false,   # Position: [x, y, z]
                   false, false, false,  # Linear velocity: [x, y, z]
                   true, true, true,     # Orientation: [roll, pitch, yaw]
                   false, false, false,  # Angular velocity: [x, y, z]
                   true, true, true,     # Orientation variance: [roll, pitch, yaw]
                   false, false, false]  # Position variance: [x, y, z]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    use_control: false

    process_noise_covariance: [1e-3, 1e-3, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom1: /gps_data
    odom1_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    odom2: /radar_odom
    odom2_config: [true, true, false,   # Position: [x, y, z]
                   false, false, false,  # Linear velocity: [x, y, z]
                   true, true, true,     # Orientation: [roll, pitch, yaw]
                   false, false, false,  # Angular velocity: [x, y, z]
                   true, true, true,     # Orientation variance: [roll, pitch, yaw]
                   false, false, false]  # Position variance: [x, y, z]
    odom2_queue_size: 10
    odom2_differential: false
    odom2_relative: false

    imu0: /imu/data
    imu0_config: [false, false, false,  # Position: [x, y, z]
                  false, false, false,  # Linear velocity: [x, y, z]
                  true, true, true,     # Orientation: [roll, pitch, yaw]
                  false, false, false,  # Angular velocity: [x, y, z]
                  true, true, true,     # Orientation variance: [roll, pitch, yaw]
                  false, false, false]  # Angular velocity variance: [x, y, z]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    use_control: false

    process_noise_covariance: [1.0, 1.0, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    initial_estimate_covariance: [1.0, 1.0, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0429351  # For lat/long 55.944831, -3.186998
    yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
    zero_altitude: false
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
