### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        sensor_timeout: 1.0
        two_d_mode: true
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true
        debug: false
        debug_out_file: /home/ws/src/robot_localization/debug.txt
        permit_corrected_publication: false
        publish_acceleration: true
        publish_tf: true
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: map
        imu0: /bno055/imu
        imu0_config: [false, false, false, false, false, true, false, false, false, false, false, true, true, true, false]
        imu0_differential: false
        imu0_relative: true
        imu0_queue_size: 5
        imu0_pose_rejection_threshold: 0.8
        imu0_twist_rejection_threshold: 0.8
        imu0_linear_acceleration_rejection_threshold: 0.8
        imu0_remove_gravitational_acceleration: false
        gps0: /gps/fix
        gps0_config: [true, true, false, false, false, false, false, false, false, false, false, false]
        gps0_queue_size: 5
        gps0_differential: false
        gps0_relative: false
        gps0_pose_rejection_threshold: 5.0
        gps0_twist_rejection_threshold: 1.0
